name: Build Doxygen on Linux and macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake flex bison python3
    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake flex bison python3
    - name: Download Doxygen 1.13.2
      run: |
        curl -L -o doxygen-1.13.2.src.tar.gz https://www.doxygen.nl/files/doxygen-1.13.2.src.tar.gz
    - name: Extract Source
      run: |
        tar -zxvf doxygen-1.13.2.src.tar.gz
    - name: Create Build Directory
      run: |
        mkdir doxygen-1.13.2/build
        cd doxygen-1.13.2/build
    - name: Configure with CMake
      run: |
        cd doxygen-1.13.2/build
        cmake -G "Unix Makefiles" ..
    - name: Compile Doxygen
      run: |
        cd doxygen-1.13.2/build
        make -j$(nproc || sysctl -n hw.ncpu)
    - name: Verify Binary
      run: |
        ls -lh doxygen-1.13.2/build/bin/doxygen
        doxygen-1.13.2/build/bin/doxygen --version
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-binary-${{ matrix.os }}
        path: doxygen-1.13.2/build/bin/doxygen